### ISSUE TITLE
yaml_parse_url method not working

### ISSUE THREAD

**Issue by miguelluiscorreia** [php/pecl-file_formats-yaml#65]
I'm trying to use the yaml_parse_url, with version 2.2.2 and is not working. The method returns NULL. 

`<?php
$data = yaml_parse_url('https://raw.githubusercontent.com/codefresh-io/yaml-examples/master/codefresh-build-1.yml');
var_dump($data);
?>`

Am I doing something wrong or is there a bug in this method?

**Comment by remicollet** [comment]
see PR #66

**Comment by miguelluiscorreia** [comment]
Thanks for the quick response. It looks fine in my understanding :)
