### ISSUE TITLE
No PHP 8.2 Windows binaries

### ISSUE THREAD

**Issue by andrey-helldar** [php/pecl-file_formats-yaml#71]
PHP 8.2 came out a few months ago and still the YAML extension doesn't support it.

Can you tell me how soon the release will be?

**Comment by bd808** [comment]
Happy #ilovefs day to you too @andrey-helldar! Thanks for using such a welcoming and friendly tone in your complaint that I have not given you enough free labor lately. I'll get back to you about your demand for a timeline right after your extended support payment shows up in my bank account.

Do you have a stacktrace or other output showing that the current release does not build on PHP 8.2? I think there is a typo in one test that 8.2 doesn't like, but as far as I know the code compiles and works with that PHP release.

**Comment by andrey-helldar** [comment]
@bd808, happy #ilovefs day! I apologize if my tone seemed incorrect. Unfortunately, I do not speak English and therefore use Google Translate. He probably misunderstood the context due to my incorrect wording of the sentence.

The most important thing that I forgot to write is the availability of the extension for Windows. And I would be happy to donate to you, but it's technically impossible - I'm in Russia and our country is disconnected from the SWIFT banking system, as well as those banks that can still make SWIFT transfers abroad using full bank details, they work only with some countries like Georgia, Kazakhstan and other CIS countries. The rest don't work.

I also started asking because [there](https://pecl.php.net/package/yaml) was no update for this package under windows.

**Comment by 0x446** [comment]
@andrey-helldar I ran into the same issue and manually build it.
I've attached you the two versions (non-thread safe and thread-safe) for x64 architectures.
Use at your own risk, I couldn't find any bugs on my end but I might not be using all of the functionalities that the library provides. I also added the Virustotal.com links to the zipped file.

[php_yaml_8.2.3.zip](https://github.com/php/pecl-file_formats-yaml/files/10824082/php_yaml_8.2.3.zip)

**Comment by andrey-helldar** [comment]
@0x446, Thanks a lot!

**Comment by Toddler-Boy** [comment]
@bd808 I'll gladly PayPal you $100 USD for a Windows build compatible with PHP 8.2 (x64, NTS)

**Comment by bd808** [comment]
> @bd808 I'll gladly PayPal you $100 USD for a Windows build compatible with PHP 8.2 (x64, NTS)

The Windows DLLs are magically produced by some set of PHP community volunteers. I have never quite understood how the builds are triggered or if I have any ability to cause new builds to be created for existing releases.

On https://pecl.php.net/package/yaml/2.2.2/windows it says "In case of missing DLLs, consider to contact the [PHP for Windows Team](https://windows.php.net/team/)."

**Comment by bd808** [comment]
On https://windows.php.net/ the current status update seems to be:
> Missing PECL DLLs  17 Oct 2022
> You may have already noticed that DLLs for new PECL releases are no longer available for several months. This is because the Windows PECL build machine died, and the team is still working on the long term plan of building DLLs for PECL extensions with a new CI process. We're doing our best to finish that as soon as possible, and keep you up to date.

**Comment by Toddler-Boy** [comment]
Thanks. I will try to get in touch with them.

**Comment by Toddler-Boy** [comment]
Here is a recent build:

https://github.com/cmb69/php-ftw/actions/runs/4303384991

Download the "artifacts" at the bottom and inside you will find all versions of this extension for PHP 8.0, 8.1, and 8.2.

**Comment by Jan-E** [comment]
For PHP 8.0.x, 8.1.x and 8.2.x I am including php_yaml.dll, compiled from git HEAD (which currently is release 2.2.3). See the zips on https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by D0ublek1ll** [comment]
> Here is a recent build:
> 
> https://github.com/cmb69/php-ftw/actions/runs/4303384991
> 
> Download the "artifacts" at the bottom and inside you will find all versions of this extension for PHP 8.0, 8.1, and 8.2.

@reFX-Mike could you also provide a build for the yaml extension version 2.2.3?

**Comment by hopeseekr** [comment]
Dear @andrey-helldar.

Please imagine that someone replied like you did in a corporate environment.

Now imagine the repercussions for that.

Even if you're having a bad day, you shouldn't be on the attack so quick like that.

**Comment by TheStaticTurtle** [comment]
See PR #82 
You can get .dll / .so from the build artifacts

**Comment by CL-Jeremy** [comment]
Did anyone metion this: https://phpext.phptools.online/extension/file-formats/yaml-330?
I'm working on another PECL extension and have contacted these nice people. Their platform looks promising.
